#ifndef PAGESNUMBERS_H
#define PAGESNUMBERS_H

enum class PageNumber
{
    LOADING,
    MAIN_MENU,
    INVOICE,
    SHOW_INVOICE,
    SUPPLIERS,
    SETTINGS,
    ADDSUPPLIER,
    QUESTION_SUPPLIER,
    CUSTOMERS,
    ADDCUSTOMER,
    QUESTION_CUSTOMER
};

#endif // PAGESNUMBERS_H
